# Agent Capabilities Configuration
# Defines which agents have file write permissions and their allowed paths

agents:
  CodeSmithAgent:
    capabilities:
      file_write: true
      allowed_paths:
        - "./backend/**/*.py"
        - "./tests/**/*.py"
        - "./examples/**/*.py"
        - "./*.py"  # Allow Python files in root directory
        - "./vscode-extension/**/*.ts"
        - "./vscode-extension/**/*.js"
        - "./**/*.ts"  # TypeScript files anywhere
        - "./*.ts"
        - "./**/*.tsx"  # React TypeScript files anywhere
        - "./*.tsx"
        - "./**/*.jsx"  # React JavaScript files anywhere
        - "./*.jsx"
        - "./**/*.js"  # JavaScript files anywhere
        - "./*.js"
        - "./**/*.html"
        - "./*.html"
        - "./**/*.css"
        - "./*.css"
        - "./**/*.json"
        - "./*.json"
        - "./**/*.yaml"
        - "./*.yaml"
        - "./**/*.md"  # Markdown files (README, docs)
        - "./*.md"
        - "./Dockerfile"  # Docker files
        - "./**/Dockerfile"
        - "./docker-compose.yml"  # Docker compose
        - "./**/*.env.example"  # Environment examples
    description: "Can write code files in various languages and formats"

  ArchitectAgent:
    capabilities:
      file_write: true
      allowed_paths:
        - "./*.config"
        - "./docker-compose.yml"
        - "./Dockerfile"
        - "./backend/config/**"
        - "./docs/architecture/**"
    description: "Can create configuration files and architecture documentation"

  FixerBot:
    capabilities:
      file_write: true
      allowed_paths:
        - "./backend/**/*.py"
        - "./vscode-extension/**/*.ts"
        - "./vscode-extension/**/*.js"
    description: "Can fix code in any supported language"

  FixerGPT:
    capabilities:
      file_write: true
      allowed_paths:
        - "./backend/**/*.py"
        - "./vscode-extension/**/*.ts"
        - "./vscode-extension/**/*.js"
        - "./**/*.html"
        - "./**/*.css"
        - "./**/*.json"
    description: "Alternative fixer using GPT (v5.1.0) - same permissions as FixerBot"

  DocuBot:
    capabilities:
      file_write: true
      allowed_paths:
        - "./docs/**"
        - "./*.md"
        - "./backend/docs/**"
    description: "Can write documentation files"

  PerformanceBot:
    capabilities:
      file_write: true
      allowed_paths:
        - "./performance/**"
        - "./benchmarks/**"
        - "./profiling/**"
    description: "Can write performance analysis results and benchmarks"

  ReviewerGPT:
    capabilities:
      file_write: false
      allowed_paths: []
    description: "Read-only agent for code review and analysis"

  ResearchBot:
    capabilities:
      file_write: false
      allowed_paths: []
    description: "Read-only agent for research and information gathering"

  OrchestratorAgent:
    capabilities:
      file_write: false
      allowed_paths: []
    description: "Coordination agent, delegates writing to specialized agents"

  OpusArbitrator:
    capabilities:
      file_write: false
      allowed_paths: []
    description: "Decision-making agent for conflict resolution"

  TradeStrat:
    capabilities:
      file_write: true
      allowed_paths:
        - "./trading/**"
        - "./strategies/**"
        - "./backtest/**"
    description: "Can write trading strategies and backtest results"

  VideoAgent:
    capabilities:
      file_write: true
      allowed_paths:
        - "./**/*.json"  # JSON output for agents
        - "./**/*.md"    # Markdown output for humans
        - "$HOME/.ki_autoagent/data/video_output/**/*"  # Global video output directory
    description: "Can analyze videos and write analysis results in JSON and Markdown formats"

# Default settings for all agents
defaults:
  backup_before_write: true
  audit_logging: true
  max_file_size_mb: 10
  protected_files:
    - "*.env"
    - "*.key"
    - "*.pem"
    - "*.secret"