version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ki_autoagent_redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --save 60 1
      --save 300 10
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3